lenguage: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vasily93markov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vasily93markov/docker-react npm run test

    deploy:
        edge: true
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-us-east-2-310600231023"
        bucket_path: "docker-react"
        on:
            branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
