sudo: required
services:
    - docker

before_install:
    - docker build -t vasily93markov/docker-react -f Dockerfile.dev .

script:
    - docker run vasily93markov/docker-react npm run test -- --coverage